library(tidyverse)
library(httr)
library(sf)
library(tmap)
library(tigris)
library(raster)
library(dplyr)
tmap_mode("view")

#proj <- 26916
proj <- 4326

basemap <- tm_basemap(c("CartoDB.Positron", "OpenStreetMap.Mapnik", "Esri.WorldImagery")) + tm_tiles("OpenRailwayMap", alpha = 0.5)

# Download FRA Data for Blocked Crossing Reports --------------------------

# The API link below may need to be updated. To do that, go to: https://www.fra.dot.gov/blockedcrossings/incidents
# Press CTRL + SHIFT + I to open devtools. Go to the Network tab, make sure Fetch/XHR is clicked and refresh the page
# The Request URL that shows up is what you could use for the URL below. 
dataRaw <- 
  GET("https://www.fra.dot.gov/blockedcrossings/api/incidents?page=1&pageSize=500000") %>% 
  content()
blockedCrossings <- dataRaw$items %>% bind_rows() %>% rename(CrossingID = crossingID)

# Import Grade Crossing Inventory Data ------------------------------------

# Read in all Current US crossing data
# Note that this file is too large to be stored on github. 
# Download "All States" file from: https://safetydata.fra.dot.gov/OfficeofSafety/publicsite/DownloadCrossingInventoryData.aspx 

xings <- 
#  read_csv("C:/Users/frryan/Desktop/_Working Files/_R/FRA/CurrentInventory/PublishedCrossingData-04-30-2022.csv", #Chris
  read_csv("C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Data/GCIS_Published_Crossing_Data/PublishedCrossingData-05-31-2022.csv", #Steph
        col_types = cols(
             MilePost = col_double())) %>%
  filter(
    !is.na(Latitude), #filter xings without lat/long
    PosXing == 1, #filter only at-grade xings
    ReasonID != 16 #filter xings that have been closed
  ) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)


GradeSepxings <- 
  #  read_csv("C:/Users/frryan/Desktop/_Working Files/_R/FRA/CurrentInventory/PublishedCrossingData-04-30-2022.csv", #Chris
  read_csv("C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Data/GCIS_Published_Crossing_Data/PublishedCrossingData-05-31-2022.csv", #Steph
           col_types = cols(
             MilePost = col_double())) %>%
  filter(
    !is.na(Latitude), #filter xings without lat/long
    PosXing != 1, #filter only at-grade xings
    ReasonID != 16 #filter xings that have been closed
  ) %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) 

# Import FRA Accident/Incident Records ------------------------------------

# The Accident data is small enough that it can be stored on GitHub

# Read in all Accident/Incident data
gcisAccHist <- map_dfr(
  c("Acc2016", "Acc2017", "Acc2018", "Acc2019", "Acc2020"),
  ~read_csv(paste0("Data/", ., ".csv"), 
            col_types = cols(.default = "c")) #default to character type to avoid conflicting autogenerated types
)

# Next step is to filter to the study area
MACOGSF <- read_sf("C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Data/Indiana Counties/d97376b1-781d-4aad-bacc-011171010eee2020413-1-1wbeqv7.muvgf.shp") %>% 
  filter(COUNTYNAME == "ELKHART" | COUNTYNAME == "KOSCIUSKO" | COUNTYNAME == "MARSHALL" | COUNTYNAME == "ST. JOSEPH") %>%
  st_transform(proj)
MACOGcounties <- c("ELKHART", "KOSCIUSKO", "MARSHALL", "ST. JOSEPH")

# Filter for MACOG data
MACOG_xings <- xings %>% st_intersection(MACOGSF)
MACOG_xingaccs <- gcisAccHist %>% filter(COUNTY %in% MACOGcounties)
IN_blockedxings <- blockedCrossings %>% filter(state == "IN")
MACOG_GradeSepxings <- GradeSepxings %>% st_intersection(MACOGSF)

#Joining Grade Crossing Inventory with Blocked Crossings Report
MACOG_xingsblocked <- inner_join(MACOG_xings, IN_blockedxings, by = "CrossingID")
#write_csv(MACOG_xingsblocked, "MACOG Blocked Crossings.csv")

# Grouping by and adding the number of times crossing was blocked
MACOG_xingsblockedCount <- as.data.frame(table(MACOG_xingsblocked$CrossingID))
colnames(MACOG_xingsblockedCount) <- c('CrossingID', 'Count')

MACOG_xingsblockedSummary <- MACOG_xingsblocked %>%
  mutate(long = unlist(map(MACOG_xingsblocked$geometry, 1)),
         lat = unlist(map(MACOG_xingsblocked$geometry, 2))) %>%
  st_drop_geometry() %>%
  left_join(MACOG_xingsblockedCount, by = "CrossingID") %>%
  group_by(CrossingID, Railroad, CityName, CountyName, Count, long, lat) %>%
  summarize() %>%
  st_as_sf(coords = c("long", "lat"), crs = 4326)


# Import Rail Lines Data (SKIP IF DONE ALREADY) ---------------------------------------------------------------
# https://geo.dot.gov/server/rest/services/NTAD/North_American_Rail_Lines/MapServer/0
# https://hub.arcgis.com/datasets/fedmaps::north-american-rail-lines/explore?location=38.799691%2C-76.791575%2C8.90

railLines <- read_sf("C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Data/North_American_Rail_Lines/North_American_Rail_Lines.shp")
railLinesMACOG <- railLines %>% st_transform(proj) %>% st_intersection(MACOGSF) %>%
  mutate(
    RROWNER1 = case_when(
      RROWNER1 == "FC" ~ "EWR",
      RROWNER1 == "CSXT" ~ "CSX",
      RROWNER1 == "NICD" ~ "NICTD",
      TRUE ~ RROWNER1
    ))

RailLinesBlockedXings <-
  tm_basemap(c("CartoDB.Positron", "OpenStreetMap.Mapnik", "Esri.WorldImagery")) +
  tm_shape(railLinesMACOG) +
      tm_lines(lwd = 4, col = "RROWNER1", id = "RROWNER1", popup.vars = FALSE, palette = "Set1", textNA = "Abandoned", title.col = "Railroad") +
  tm_shape(MACOG_xingsblockedSummary) +
      tm_dots(size = "Count", scale = 2, alpha = 0.5, col = "grey30", id = "Count", popup.vars = c("CrossingID", "Railroad", "CityName", "CountyName"), legend.size.show = TRUE, legend.size.is.portrait = TRUE) +
      tm_add_legend(type = "fill", labels = "Frequency of Grade Crossing Blockages", col = "grey30") +
  tm_shape(MACOG_xings) +
      tm_dots(col = "darkorange2", popup.vars = FALSE, size = 0.01) +
  tm_shape(MACOG_GradeSepxings) +
      tm_dots(col = "chartreuse3", popup.vars = FALSE, size = 0.01) +
  tm_shape(MACOGSF) + tm_borders()

tmap_save(RailLinesBlockedXings, "C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Maps/MACOG Blocked Grade Crossings.html")



