library(tidyverse)
library(httr)
library(sf)
library(tmap)
library(tigris)
library(raster)
library(dplyr)
tmap_mode("view")

#proj <- 26916
proj <- 4326

basemap <- tm_basemap(c("CartoDB.Positron", "OpenStreetMap.Mapnik", "Esri.WorldImagery")) + tm_tiles("OpenRailwayMap", alpha = 0.5)

# Download FRA Data for Blocked Crossing Reports --------------------------

# The API link below may need to be updated. To do that, go to: https://www.fra.dot.gov/blockedcrossings/incidents
# Press CTRL + SHIFT + I to open devtools. Go to the Network tab, make sure Fetch/XHR is clicked and refresh the page
# The Request URL that shows up is what you could use for the URL below. 
dataRaw <- 
  GET("https://www.fra.dot.gov/blockedcrossings/api/incidents?page=1&pageSize=500000") %>% 
  content()
blockedCrossings <- dataRaw$items %>% bind_rows() %>% rename(CrossingID = crossingID)

# Import Grade Crossing Inventory Data ------------------------------------

# Read in all Current US crossing data
# Note that this file is too large to be stored on github. 
# Download "All States" file from: https://safetydata.fra.dot.gov/OfficeofSafety/publicsite/DownloadCrossingInventoryData.aspx 

xings <- 
#  read_csv("C:/Users/frryan/Desktop/_Working Files/_R/FRA/CurrentInventory/PublishedCrossingData-04-30-2022.csv", #Chris
  read_csv("C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Data/GCIS_Published_Crossing_Data/PublishedCrossingData-05-31-2022.csv", #Steph
        col_types = cols(
             MilePost = col_double())) %>%
  filter(
    !is.na(Latitude), #filter xings without lat/long
    PosXing == 1, #filter only at-grade xings
    ReasonID != 16 #filter xings that have been closed
  ) %>%
  mutate(CrossingType = "At-Grade") %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)


GradeSepxings <- 
  #  read_csv("C:/Users/frryan/Desktop/_Working Files/_R/FRA/CurrentInventory/PublishedCrossingData-04-30-2022.csv", #Chris
  read_csv("C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Data/GCIS_Published_Crossing_Data/PublishedCrossingData-05-31-2022.csv", #Steph
           col_types = cols(
             MilePost = col_double())) %>%
  filter(
    !is.na(Latitude), #filter xings without lat/long
    PosXing != 1, #filter only at-grade xings
    ReasonID != 16 #filter xings that have been closed
  ) %>%
  mutate(CrossingType = "Grade-Separated") %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)

allXings <- rbind(xings, GradeSepxings)


# Import FRA Accident/Incident Records ------------------------------------

# The Accident data is small enough that it can be stored on GitHub

# Read in all Accident/Incident data
gcisAccHist <- map_dfr(
  c("Acc2016", "Acc2017", "Acc2018", "Acc2019", "Acc2020"),
  ~read_csv(paste0("Data/", ., ".csv"), 
            col_types = cols(.default = "c")) #default to character type to avoid conflicting autogenerated types
)

# Import Rail Lines Data (SKIP IF DONE ALREADY) ---------------------------------------------------------------
# https://geo.dot.gov/server/rest/services/NTAD/North_American_Rail_Lines/MapServer/0
# https://hub.arcgis.com/datasets/fedmaps::north-american-rail-lines/explore?location=38.799691%2C-76.791575%2C8.90
railLines <- read_sf("C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Data/North_American_Rail_Lines/North_American_Rail_Lines.shp") %>%
  mutate(RROWNER1 = case_when(
    RROWNER1 == "FC" ~ "EWR",
    RROWNER1 == "CSXT" ~ "CSX",
    RROWNER1 == "NICD" ~ "NICTD",
    TRUE ~ RROWNER1))

railYards <- railLines %>% filter(NET == ("Y"), !is.na(YARDNAME))

###------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## Begin analysis on study area
MACOGSF <- read_sf("C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Data/Indiana Counties/d97376b1-781d-4aad-bacc-011171010eee2020413-1-1wbeqv7.muvgf.shp") %>% 
  filter(COUNTYNAME == "ELKHART" | COUNTYNAME == "KOSCIUSKO" | COUNTYNAME == "MARSHALL" | COUNTYNAME == "ST. JOSEPH") %>%
  st_transform(proj)
MACOGcounties <- c("ELKHART", "KOSCIUSKO", "MARSHALL", "ST. JOSEPH")

# Filter all data for MACOG
MACOG_xings <- xings %>% st_intersection(MACOGSF)
IN_blockedxings <- blockedCrossings %>% filter(state == "IN")
MACOG_allXings <- allXings %>% st_intersection(MACOGSF)
MACOG_railLines <- railLines %>% st_intersection(MACOGSF)
MACOG_railYards <- railYards %>% st_intersection(MACOGSF)
MACOG_xingaccs <- gcisAccHist %>% filter(COUNTY %in% MACOGcounties, STATE == "18")  %>%
  filter(
    GXID != "916991G", # closed crossing since November 2019
    GXID != "510037X" # closed crossing since December 2021
  ) %>%
  mutate(CrossingID = GXID)


###------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## BLOCKED CROSSINGS COMPLAINTS
# Joining Grade Crossing Inventory with Blocked Crossings Complaint Report Data
MACOG_xingsblocked <- inner_join(MACOG_xings, IN_blockedxings, by = "CrossingID")
#write_csv(MACOG_xingsblocked, "MACOG Blocked Crossings.csv")

# Grouping by and adding the number of times crossing was blocked
MACOG_xingsblockedCount <- as.data.frame(table(MACOG_xingsblocked$CrossingID))
colnames(MACOG_xingsblockedCount) <- c('CrossingID', 'Count')

MACOG_xingsblockedSummary <- MACOG_xingsblocked %>%
  mutate(long = unlist(map(MACOG_xingsblocked$geometry, 1)),
         lat = unlist(map(MACOG_xingsblocked$geometry, 2))) %>%
  st_drop_geometry() %>%
  left_join(MACOG_xingsblockedCount, by = "CrossingID") %>%
  group_by(CrossingID, Railroad, CityName, CountyName, Count, long, lat) %>%
  summarize() %>%
  st_as_sf(coords = c("long", "lat"), crs = 4326)

# Just renaming for tmap view mode purposes
Rail_Lines <- railLinesMACOG
Rail_Yards <- railYardsMACOG
Blocked_Crossings <- MACOG_xingsblockedSummary %>% mutate(BlockedCrossingReports = Count)
Grade_Crossings <- MACOG_allXings
MACOG_Boundary <- MACOGSF

RailLinesBlockedXings <-
  tm_basemap(c("CartoDB.Positron", "OpenStreetMap.Mapnik", "Esri.WorldImagery")) +
  tm_shape(MACOG_Boundary) + tm_borders() +
  tm_shape(Rail_Yards) +
      tm_lines(lwd = 10, col = "black", id = "RROWNER1", popup.vars = FALSE, title.col = "Rail Yards") +
      #tm_text("YARDNAME", size = 0.8, col = "gray10", ymod = 0.5) +
      tm_add_legend(type = "fill", labels = "Rail Yards", col = "black") +
  tm_shape(Blocked_Crossings) +
      tm_dots(col = "BlockedCrossingReports", size = "BlockedCrossingReports", scale = 2, alpha = 0.5, palette = "YlOrBr", id = "Count", popup.vars = c("CrossingID", "Railroad", "CityName", "CountyName"), legend.size.show = TRUE, title = "Blocked Crossing Reports") +
  tm_shape(Rail_Lines) +
      tm_lines(lwd = 3, col = "RROWNER1", id = "RROWNER1", popup.vars = FALSE, palette = "Set3", textNA = "Abandoned", title.col = "Railroad") +
  tm_shape(Grade_Crossings) +
      tm_dots(col = "CrossingType", palette = "RdBu", alpha = 0.75, popup.vars = FALSE, size = 0.01, title = "Crossing Type")

tmap_save(RailLinesBlockedXings, "C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Maps/MACOG Blocked Crossings.html")
write_csv(Blocked_Crossings, "C:/Users/sferzli/Documents/Projects/US/MACOG/Grade Crossing Analysis/Results/Blocked Crossings Recorded Complaints.csv")


###------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## CROSSING CRASHES (LAST 5 YEARS)
# Processing 5-year Crossing Incident Data
MACOG_xingaccs5yr <- MACOG_xingaccs %>%
  mutate(CrashYear = 2000 + as.numeric(YEAR)) %>%
  #filter(CrashYear >= 2016) %>% 
  mutate(severity = case_when(
    as.numeric(TOTKLD) > 0 ~ "Fatal",
    as.numeric(TOTINJ) > 0 ~ "Injury",
    TRUE ~ "PDO"
  )) %>%
  group_by(GXID, severity) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = "severity", values_from = "count", values_fill = 0) %>%
  mutate(Total5yr = sum(c_across(Injury:Fatal)))

# Joining 5-year Crossing Incident Data to FRA Crossing Inventory Data
MACOG_RailCrossingIncidents <- MACOG_xingaccs %>%
  inner_join(MACOG_xingaccs5yr, by = c("CrossingID" = "GXID"))

MACOG_RailCrossingIncidents_shp <- MACOG_xingaccs %>%
  inner_join(MACOG_xingaccs5yr, by = c("CrossingID" = "GXID")) %>%
  left_join(MACOG_xings %>%
              mutate(long = unlist(map(MACOG_xings$geometry, 1)),
                     lat = unlist(map(MACOG_xings$geometry, 2))),
            by = "CrossingID") %>%
  st_as_sf(coords = c("long", "lat"), crs = 4326)


###------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## SPEEDS AND VOLUMES
# Crosswalk table between operating RR and RR Owner
railNameLookup <- tibble(
  CrossingIdSuffix = c("CFE", "CN", "CSS", "CSX", "ELWX", "GDLK", "GER", "GTW", "NICD", "NS"),
  RRname           = c("CFE", "CN", "CSS", "CSX","EWR", "GDLK", "GDLK", "CN",  "NICTD", "NS"))

# Add RR names and calculate daily train volumes (doesn't include switching)
MACOG_xings2 <- MACOG_xings %>% left_join(railNameLookup) %>% mutate(trainTot = DayThru + NghtThru)

getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

# Join crossing data to rail line data to calculate train speed and volumes
railJoin <- st_join(MACOG_xings2, MACOG_railLines, join = st_nearest_feature) %>% st_drop_geometry() %>%
  dplyr::select(OBJECTID = OBJECTID.y, RROWNER1, trainTot, MaxTtSpd) %>% group_by(OBJECTID) %>% 
  summarize(
    trains = getmode(trainTot),
    speed = getmode(MaxTtSpd)
  )

# Add the speed and volume information to the rail line data for mainlines only
# Then split it and join the unknown data to the known data and recombine
MACOG_railLines_Join1 <- MACOG_railLines %>%
  left_join(railJoin) %>%
  filter(NET %in% c("M")) %>%
  dplyr::select(OBJECTID, COUNTYNAME, RROWNER1, trains, speed)
railJoinKnown <- MACOG_railLines_Join1 %>% filter(!is.na(trains))
railJoinEmpty <- MACOG_railLines_Join1 %>% filter(is.na(trains))

missingDataJoin <- st_join(railJoinEmpty, railJoinKnown, join = st_nearest_feature) %>% 
  dplyr::select(OBJECTID = OBJECTID.x, COUNTYNAME = COUNTYNAME.x, RROWNER = RROWNER1.x, trains = trains.y, speed = speed.y) %>% st_drop_geometry()

# Manually adjusting train volumes on NS line // FRA supposed inaccurate data
MACOG_railLines_SpdVol <- MACOG_railLines_Join1 %>% left_join(missingDataJoin, by = "OBJECTID") %>%
  rowwise() %>%
  transmute(
    OBJECTID = OBJECTID,
    COUNTYNAME = COUNTYNAME.x,
    RROWNER1 = RROWNER1,
    trains = max(trains.x, trains.y, na.rm = TRUE),
    speed = max(speed.x, speed.y, na.rm = TRUE)
  ) %>%
  mutate(
    new_trains = case_when(
      (COUNTYNAME == "ST. JOSEPH" & RROWNER1 == "NS" & trains < 20) ~ 60,
      (COUNTYNAME == "ELKHART" & RROWNER1 == "NS" & trains < 5) ~ 60,
      TRUE ~ trains
    ),
    new_speed = case_when(
      (COUNTYNAME == "ST. JOSEPH" & RROWNER1 == "NS" & trains < 20) ~ 79,
      (COUNTYNAME == "ELKHART" & RROWNER1 == "NS" & trains < 5) ~ 79,
      TRUE ~ speed
    )
  )


###------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
## Crossing with HIGH SWTICHING TRAIN VOLUMES and HIGH WEEKLY TRAIN VOLUMES
# Summarize number of crossings by number of switching trains per day
MACOG_xings_SwtCount <- as.data.frame(table(MACOG_xings$TotalSwt))
colnames(MACOG_xings_SwtCount) <- c('TotalSwt', 'NumbofCrossings')

# Check for 90th percentile
quantile(MACOG_xings$TotalSwt, 0.99) #6

# Filter for top 1% in number of switching trains
MACOG_xings_highSwt <- MACOG_xings %>%
  filter(TotalSwt > 6) %>%
  mutate(TotalSwt2 = as.character(TotalSwt))

tm_basemap(c("CartoDB.Positron", "OpenStreetMap.Mapnik", "Esri.WorldImagery")) +
  tm_shape(MACOG_Boundary) + tm_borders() +
  tm_shape(Rail_Lines) +
  tm_lines(lwd = 3, col = "RROWNER1", id = "RROWNER1", popup.vars = FALSE, palette = "Set3", textNA = "Abandoned", title.col = "Railroad") +
  tm_shape(MACOG_xings_highSwt) +
  tm_dots(col = "TotalSwt2", palette = "Dark2", alpha = 1, popup.vars = FALSE, size = 0.01, title = "Number of Switching Trains")

# CrossingID = 522576V has the highest number of total switching trains (13 per day).
# This crossing is located on the NS line near New Carlisle near the Northwestern border of St. Joseph County.
# CrossingID = 533572Y has the second highest number of total switching trains (9 per day).
# This crossing is located on the NS line in Warsaw.
# CrossingID = 533573F has the tird highest number of total switching trains (7 per day).
# This crossing is located on the NS line in Warsaw as well.


